server:
  port: 10001
  servlet:
    context-path: /gunpla-decal

app:
  db-path: ${DB_PATH}
  base-url: ${BASE_URL}
  ga4: G-1T1RL1L7ZD
  gtm-id: GTM-5RDNJ7TR

decorator:
  datasource:
    enabled: false
